#!/bin/bash

#COLORED OUTPUT
readonly RED='\033[0;31m'
readonly BLUE='\033[1;36m'
readonly GREEN='\033[0;32m'
readonly RESET='\033[0m'

#IS AN ARGUMENT GIVEN?
if [ "${#}" -ne 1 ]; then
        printf "${RED}Missing message${RESET}\nUsage: %s <MESSAGE>\n" "$(basename "${0}")"
        exit 1
fi

#----------------------------------------------------------------------

#VARIABLES
readonly MESSAGE="${1}"
if ! readonly PTY="$(ls /dev/pts/ 2>/dev/null)" || ! readonly PTY_LIST=(${PTY}) || ! readonly OWN="$(basename "$(tty)")";then
	printf "${RED}An error occurred${RESET}\n"
	exit 1
fi

#CHECK: ARE THERE OTHER SHELLS? (PTS)
if [[ "${#PTY_LIST[@]}" -eq 2 && "${PTY_LIST[0]}" -eq "${OWN}" && "${PTY_LIST[1]}" == "ptmx" ]]; then
	printf "${BLUE}No other shells${RESET}\n"
	exit 0
fi

#----------------------------------------------------------------------

printf "${BLUE}[+] Starting script${RESET}\n\n"

for pts in "${PTY_LIST[@]}"; do
	if [[ "${pts}" =~ ^[0-9]+$ ]] && [ "${pts}" -ne "${OWN}" ]; then
		if printf "${MESSAGE}" 2>/dev/null >/dev/pts/"${pts}"; then
			printf "${GREEN}Message send to pts:%4s${RESET}\n" "${pts}"
		else
			printf "${RED}Error with pts:%9s${RESET}\n" "${pts}"
		fi
	fi
done

printf "\n${BLUE}[+] Done${RESET}\n"
