#!/bin/bash

readonly RED='\033[0;31m'
readonly BLUE='\033[1;36m'
readonly GREEN='\033[0;32m'
readonly GREEN_ITALIC='\033[3;32m'
readonly RESET='\033[0m'

usage () {
	printf -- "Usage: %s [-k|-m] [-a|-s]\n\n" "$(basename "${0}")"
        printf -- "  -k:\tKill ..\n"
	printf -- "  -m:\tMessage ..\t\tEx. \"Hey how are you\"\n"
        printf -- "  -a:\t.. all pts's\n"
	printf -- "  -s:\t.. selected pts's\tEx. 1,3,7\n\n"
	printf -- "  -l:\tList all connected pts's\n"
	printf -- "  -h:\tShow help (this screen)\n"
}

get_all_pts () {
	ALL="$(ls /dev/pts/)"
	mapfile -t LIST <<< "${ALL}"
}

get_own_pts () {
	OWN="$(basename "$(tty)")"
}

while getopts ":m:kas:hl" flag; do
	case "${flag}" in
		m)
			MESSAGE="${OPTARG}"
		;;
		k)
			KILL=1
		;;
		a)
			get_all_pts
		;;
		s)
			SELECTED="${OPTARG}"
			IFS="," read -r -a LIST <<< "${SELECTED}"
		;;
		h)
                        usage
                        exit 0
		;;
		l)
			get_all_pts
			get_own_pts
			printf "%b%-10sIP%b\n" "${GREEN_ITALIC}" "PTS" "${RESET}"
			for pts in "${LIST[@]}"; do
				if [[ "${pts}" =~ ^[0-9]+$ ]]; then
					if [ "${pts}" == "${OWN}" ];then
						extra=" (this pts)"
					fi
					ip="$(who --ips | grep "pts/${pts}" | awk '{print $5}')"
					if [ -z "${ip}" ]; then
						ip="N/A"
					fi
					printf "%bpts/%-6s%s %s%b\n" "${GREEN}" "${pts}" "${ip}" "${extra}" "${RESET}"
					unset extra
				fi
			done
			exit 0
		;;
		\?)
			printf "%bInvalid flag: -%s%b\n" "${RED}" "${OPTARG}" "${RESET}"
			usage
			exit 1
		;;
		:)
			printf "%bMissing argument for flag: -%s%b\n" "${RED}" "${OPTARG}" "${RESET}"
			usage
			exit 1
		;;
	esac
done

if [[ -v MESSAGE && -v KILL || -v ALL && -v SELECTED || ! -v MESSAGE && ! -v KILL || ! -v ALL && ! -v SELECTED ]]; then
	printf "%bMissing or wrong flag combinations%b\n" "${RED}" "${RESET}"
	usage
	exit 1
fi

get_own_pts

SPACING=22

error_message () {
	printf "%b%-${SPACING}s%s%b\n" "${RED}" "Error with pts:" "${1}" "${RESET}"
}

#----------------------------------------------------------------------

printf "%b[+] Running script%b\n\n" "${BLUE}" "${RESET}"

for pts in "${LIST[@]}"; do
	if [ "${pts}" == "${OWN}" ]; then
		printf "%b%-${SPACING}s%s%b\n" "${RED}" "Ignored own pts:" "${pts}" "${RESET}"
		continue
	fi

	if [[ "${pts}" =~ ^[0-9]+$ ]]; then
		if [ -v MESSAGE ]; then
			if printf "%s" "${MESSAGE}" 2>/dev/null >/dev/pts/"${pts}"; then
				printf "%b%-${SPACING}s%s%b\n" "${GREEN}" "Message send to pts:" "${pts}" "${RESET}"
			else
				error_message "${pts}"
			fi
			continue
		fi
		if [ -v KILL ]; then
			if kill -1 "$(ps --no-headers -ft pts/"${pts}" 2>/dev/null | awk '{print $2;exit}')" 2>/dev/null; then
				printf "%b%-${SPACING}s%s%b\n" "${GREEN}" "Killed pts:" "${pts}" "${RESET}"
			else
				error_message "${pts}"
			fi
		fi
	fi
done

printf "\n%b[+] Done%b\n" "${BLUE}" "${RESET}"
