#!/bin/bash

#COLORED OUTPUT
readonly RED='\033[0;31m'
readonly BLUE='\033[1;36m'
readonly GREEN='\033[0;32m'
readonly RESET='\033[0m'

#FUNCTION OUTPUT USAGE
usage () {
	printf -- "Usage: %s [-k|-m] [-a|-s]\n\n" "$(basename "${0}")"
        printf -- "  -k:\tKill ..\n"
	printf -- "  -m:\tMessage ..\t\tEx. \"Hey how are you\"\n"
        printf -- "  -a:\t.. all pts's\n"
	printf -- "  -s:\t.. selected pts's\tEx. 1,3,7\n\n"
	printf -- "  -l:\tList all connected pts's\n"
	printf -- "  -h:\tShow help (this screen)\n"
}

#FUNCTION LIST ALL CONNECTED PTS'S
get_all_pts () {
	ALL="$(ls /dev/pts/)"
	mapfile -t LIST <<< "${ALL}"
}

#FUNCTION GET OWN PTS
get_own_pts () {
	OWN="$(basename "$(tty)")"
}

#PROGRAM FLAG SUPPORT
while getopts ":m:kas:hl" flag; do
	case "${flag}" in
		m)
			readonly MESSAGE="${OPTARG}"
		;;
		k)
			readonly KILL=1
		;;
		a)
			get_all_pts
		;;
		s)
			readonly SELECTED="${OPTARG}"
			IFS="," read -r -a LIST <<< "${SELECTED}"
		;;
		h)
                        usage
                        exit 0
		;;
		l)
			get_all_pts
			get_own_pts
			for pts in "${LIST[@]}"; do
				if [[ "${pts}" =~ ^[0-9]+$ ]]; then
					if [ "${pts}" == "${OWN}" ];then
						extra=" (this pts)"
					fi
					printf "${GREEN}/dev/pts/%s%s${RESET}\n" "${pts}" "${extra}"
					unset extra
				fi
			done
			exit 0
		;;
		\?)
			printf "${RED}Invalid flag: -%s${RESET}\n" "${OPTARG}"
			usage
			exit 1
		;;
		:)
			printf "${RED}Missing argument for flag: -%s${RESET}\n" "${OPTARG}"
			usage
			exit 1
		;;
	esac
done

#EXTRA FLAG LOGIC
if [[ -v MESSAGE && -v KILL || -v ALL && -v SELECTED || ! -v MESSAGE && ! -v KILL || ! -v ALL && ! -v SELECTED ]]; then
	printf "${RED}Missing or wrong flag combinations${RESET}\n"
	usage
	exit 1
fi

#OTHER VARIABLES
get_own_pts

#----------------------------------------------------------------------

readonly SPACING=22

error_message () {
	printf "${RED}%-${SPACING}s%s${RESET}\n" "Error with pts:" "${1}"
}

printf "${BLUE}[+] Starting script${RESET}\n\n"

for pts in "${LIST[@]}"; do
	if [ "${pts}" != "${OWN}" ]; then
		if [[ "${pts}" =~ ^[0-9]+$ ]]; then
			if [ -v MESSAGE ]; then
				if printf "%s" "${MESSAGE}" 2>/dev/null >/dev/pts/"${pts}"; then
					printf "${GREEN}%-${SPACING}s%s${RESET}\n" "Message send to pts:" "${pts}"
				else
					error_message "${pts}"
				fi
				continue
			fi
			if [ -v KILL ]; then
				if kill -1 "$(ps --no-headers -ft pts/"${pts}" 2>/dev/null | awk '{print $2;exit}')" 2>/dev/null; then
					printf "${GREEN}%-${SPACING}s%s${RESET}\n" "Killed pts:" "${pts}"
				else
					error_message "${pts}"
				fi
			fi
		fi
	else
		printf "${RED}%-${SPACING}s%s${RESET}\n" "Ignored own pts:" "${pts}"
	fi
done

printf "\n${BLUE}[+] Done${RESET}\n"
